[package]
name = "monolith"
version = "0.1.0"
edition = "2021"

[dependencies]
glam = "0.28.0"
glutin = "0.32.1"
libc = "0.2.155"
nalgebra = "0.33.0"
raw-window-handle = "0.6.2"
tao = "0.28.1"

[build-dependencies]
bindgen = "0.69.4"
